# metamodel_version: 1.7.0
# version: 3.0.1
enum AnnotationType
  {
    other
    review
  }

enum ConfidentialityLevelType
  {
    amber
    clear
    green
    red
  }

enum ContentIdentifierType
  {
    gitoid
    swhid
  }

enum CvssSeverityType
  {
    critical
    high
    low
    medium
    none
  }

enum DatasetAvailabilityType
  {
    clickthrough
    directDownload
    query
    registration
    scrapingScript
  }

enum DatasetType
  {
    audio
    categorical
    graph
    image
    noAssertion
    numeric
    other
    sensor
    structured
    syntactic
    text
    timeseries
    timestamp
    video
  }

enum EnergyUnitType
  {
    kilowattHour
    megajoule
    other
  }

enum ExploitCatalogType
  {
    kev
    other
  }

enum ExternalIdentifierType
  {
    cpe22
    cpe23
    cve
    email
    gitoid
    other
    packageUrl
    securityOther
    swhid
    swid
    urlScheme
  }

enum ExternalRefType
  {
    altDownloadLocation
    altWebPage
    binaryArtifact
    bower
    buildMeta
    buildSystem
    certificationReport
    chat
    componentAnalysisReport
    cwe
    documentation
    dynamicAnalysisReport
    eolNotice
    exportControlAssessment
    funding
    issueTracker
    license
    mailingList
    mavenCentral
    metrics
    npm
    nuget
    other
    privacyAssessment
    productMetadata
    purchaseOrder
    qualityAssessmentReport
    releaseHistory
    releaseNotes
    riskAssessment
    runtimeAnalysisReport
    secureSoftwareAttestation
    securityAdversaryModel
    securityAdvisory
    securityFix
    securityOther
    securityPenTestReport
    securityPolicy
    securityThreatModel
    socialMedia
    sourceArtifact
    staticAnalysisReport
    support
    vcs
    vulnerabilityDisclosureReport
    vulnerabilityExploitabilityAssessment
  }

enum FileKindType
  {
    directory
    file
  }

enum HashAlgorithm
  {
    adler32
    blake2b256
    blake2b384
    blake2b512
    blake3
    crystalsDilithium
    crystalsKyber
    falcon
    md2
    md4
    md5
    md6
    other
    sha1
    sha224
    sha256
    sha384
    sha3_224
    sha3_256
    sha3_384
    sha3_512
    sha512
  }

enum LifecycleScopeType
  {
    build
    design
    development
    other
    runtime
    test
  }

enum PresenceType
  {
    no
    noAssertion
    yes
  }

enum ProfileIdentifierType
  {
    ai
    build
    core
    dataset
    expandedLicensing
    extension
    lite
    security
    simpleLicensing
    software
  }

enum RelationshipCompleteness
  {
    complete
    incomplete
    noAssertion
  }

enum RelationshipType
  {
    affects
    amendedBy
    ancestorOf
    availableFrom
    configures
    contains
    coordinatedBy
    copiedTo
    delegatedTo
    dependsOn
    descendantOf
    describes
    doesNotAffect
    expandsTo
    exploitCreatedBy
    fixedBy
    fixedIn
    foundBy
    generates
    hasAddedFile
    hasAssessmentFor
    hasAssociatedVulnerability
    hasConcludedLicense
    hasDataFile
    hasDeclaredLicense
    hasDeletedFile
    hasDependencyManifest
    hasDistributionArtifact
    hasDocumentation
    hasDynamicLink
    hasEvidence
    hasExample
    hasHost
    hasInput
    hasMetadata
    hasOptionalComponent
    hasOptionalDependency
    hasOutput
    hasPrerequisite
    hasProvidedDependency
    hasRequirement
    hasSpecification
    hasStaticLink
    hasTest
    hasTestCase
    hasVariant
    invokedBy
    modifiedBy
    other
    packagedBy
    patchedBy
    publishedBy
    reportedBy
    republishedBy
    serializedInArtifact
    testedOn
    trainedOn
    underInvestigationFor
    usesTool
  }

enum SafetyRiskAssessmentType
  {
    high
    low
    medium
    serious
  }

enum SbomType
  {
    analyzed
    build
    deployed
    design
    runtime
    source
  }

enum SoftwarePurpose
  {
    application
    archive
    bom
    configuration
    container
    data
    device
    deviceDriver
    diskImage
    documentation
    evidence
    executable
    file
    filesystemImage
    firmware
    framework
    install
    library
    manifest
    model
    module
    operatingSystem
    other
    patch
    platform
    requirement
    source
    specification
    test
  }

enum SsvcDecisionType
  {
    act
    attend
    track
    trackStar
  }

enum SupportType
  {
    deployed
    development
    endOfSupport
    limitedSupport
    noAssertion
    noSupport
    support
  }

enum VexJustificationType
  {
    componentNotPresent
    inlineMitigationsAlreadyExist
    vulnerableCodeCannotBeControlledByAdversary
    vulnerableCodeNotInExecutePath
    vulnerableCodeNotPresent
  }

interface Agent
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
  }

type AIPackage
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardName: [String]
    builtTime: String
    validUntilTime: String
    supportLevel: [SupportType]
    suppliedBy: Agent
    originatedBy: [Agent]
    releaseTime: String
    attributionText: [String]
    primaryPurpose: String
    additionalPurpose: [String]
    contentIdentifier: [ContentIdentifier]
    copyrightText: String
    sourceInfo: String
    homePage: String
    downloadLocation: String
    packageVersion: String
    packageUrl: String
    informationAboutTraining: String
    modelDataPreprocessing: [String]
    typeOfModel: [String]
    safetyRiskAssessment: SafetyRiskAssessmentType
    metricDecisionThreshold: [DictionaryEntry]
    useSensitivePersonalInformation: PresenceType
    energyConsumption: EnergyConsumption
    limitation: String
    hyperparameter: [DictionaryEntry]
    autonomyType: PresenceType
    domain: [String]
    modelExplainability: [String]
    informationAboutApplication: String
    metric: [DictionaryEntry]
    standardCompliance: [String]
  }

type Annotation
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    contentType: String
    statement: String
    subject: Element!
    annotationType: String!
  }

interface AnyLicenseInfo
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
  }

interface Artifact
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardName: [String]
    builtTime: String
    validUntilTime: String
    supportLevel: [SupportType]
    suppliedBy: Agent
    originatedBy: [Agent]
    releaseTime: String
  }

interface Bom
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    element: [Element]
    profileConformance: [ProfileIdentifierType]
    rootElement: [Element]
    context: String
  }

type Build
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    buildType: String!
    buildEndTime: String
    buildId: String
    configSourceDigest: [Hash]
    buildStartTime: String
    configSourceUri: [String]
    parameter: [DictionaryEntry]
    configSourceEntrypoint: [String]
    environment: [DictionaryEntry]
  }

type Bundle
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    element: [Element]
    profileConformance: [ProfileIdentifierType]
    rootElement: [Element]
    context: String
  }

type CdxPropertiesExtension
  {
    cdxProperty: [CdxPropertyEntry]!
  }

type CdxPropertyEntry
  {
    cdxPropValue: String
    cdxPropName: String!
  }

type ConjunctiveLicenseSet
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    member: [AnyLicenseInfo]!
  }

type ContentIdentifier
  {
    comment: String
    contentIdentifierValue: String!
    contentIdentifierType: ContentIdentifierType!
  }

type CreationInfo
  {
    createdBy: [Agent]!
    createdUsing: [Tool]
    created: String!
    specVersion: String!
    comment: String
  }

type CustomLicense
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    obsoletedBy: String
    standardLicenseHeader: String
    seeAlso: [String]
    isFsfLibre: Boolean
    isDeprecatedLicenseId: Boolean
    isOsiApproved: Boolean
    licenseXml: String
    licenseText: String!
    standardLicenseTemplate: String
  }

type CustomLicenseAddition
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardAdditionTemplate: String
    seeAlso: [String]
    obsoletedBy: String
    licenseXml: String
    isDeprecatedAdditionId: Boolean
    additionText: String!
  }

type CvssV2VulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    vectorString: String!
    score: Float!
  }

type CvssV3VulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    severity: CvssSeverityType!
    vectorString: String!
    score: Float!
  }

type CvssV4VulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    severity: CvssSeverityType!
    vectorString: String!
    score: Float!
  }

type DatasetPackage
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardName: [String]
    builtTime: String
    validUntilTime: String
    supportLevel: [SupportType]
    suppliedBy: Agent
    originatedBy: [Agent]
    releaseTime: String
    attributionText: [String]
    primaryPurpose: String
    additionalPurpose: [String]
    contentIdentifier: [ContentIdentifier]
    copyrightText: String
    sourceInfo: String
    homePage: String
    downloadLocation: String
    packageVersion: String
    packageUrl: String
    datasetSize: Int
    datasetType: [String]!
    anonymizationMethodUsed: [String]
    datasetUpdateMechanism: String
    dataCollectionProcess: String
    knownBias: [String]
    sensor: [DictionaryEntry]
    dataPreprocessing: [String]
    intendedUse: String
    confidentialityLevel: ConfidentialityLevelType
    datasetAvailability: DatasetAvailabilityType
    hasSensitivePersonalInformation: PresenceType
    datasetNoise: String
  }

type DictionaryEntry
  {
    value: String
    key: String!
  }

type DisjunctiveLicenseSet
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    member: [AnyLicenseInfo]!
  }

interface Element
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
  }

interface ElementCollection
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    element: [Element]
    profileConformance: [ProfileIdentifierType]
    rootElement: [Element]
  }

type EnergyConsumption
  {
    finetuningEnergyConsumption: [EnergyConsumptionDescription]
    inferenceEnergyConsumption: [EnergyConsumptionDescription]
    trainingEnergyConsumption: [EnergyConsumptionDescription]
  }

type EnergyConsumptionDescription
  {
    energyQuantity: Float!
    energyUnit: String!
  }

type EpssVulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    percentile: Float!
    probability: Float!
  }

type ExploitCatalogVulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    exploited: Boolean!
    securityLocator: String!
    catalogType: String!
  }

interface ExtendableLicense
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
  }

interface Extension
  {
  }

type ExternalIdentifier
  {
    identifierLocator: [String]
    externalIdentifierType: String!
    issuingAuthority: String
    identifier: String!
    comment: String
  }

type ExternalMap
  {
    definingArtifact: Artifact
    locationHint: String
    externalSpdxId: String!
    verifiedUsing: [IntegrityMethod]
  }

type ExternalRef
  {
    coreLocator: [String]
    externalRefType: String
    comment: String
    contentType: String
  }

type File
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardName: [String]
    builtTime: String
    validUntilTime: String
    supportLevel: [SupportType]
    suppliedBy: Agent
    originatedBy: [Agent]
    releaseTime: String
    attributionText: [String]
    primaryPurpose: String
    additionalPurpose: [String]
    contentIdentifier: [ContentIdentifier]
    copyrightText: String
    fileKind: FileKindType
    contentType: String
  }

type Hash
  {
    comment: String
    algorithm: String!
    hashValue: String!
  }

type IndividualElement
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
  }

type IndividualLicensingInfo
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
  }

interface IntegrityMethod
  {
    comment: String
  }

interface License
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    obsoletedBy: String
    standardLicenseHeader: String
    seeAlso: [String]
    isFsfLibre: Boolean
    isDeprecatedLicenseId: Boolean
    isOsiApproved: Boolean
    licenseXml: String
    licenseText: String!
    standardLicenseTemplate: String
  }

interface LicenseAddition
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardAdditionTemplate: String
    seeAlso: [String]
    obsoletedBy: String
    licenseXml: String
    isDeprecatedAdditionId: Boolean
    additionText: String!
  }

type LicenseExpression
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    customIdToUri: [DictionaryEntry]
    licenseExpression: String!
    licenseListVersion: String
  }

type LifecycleScopedRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    scope: String
  }

type ListedLicense
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    obsoletedBy: String
    standardLicenseHeader: String
    seeAlso: [String]
    isFsfLibre: Boolean
    isDeprecatedLicenseId: Boolean
    isOsiApproved: Boolean
    licenseXml: String
    licenseText: String!
    standardLicenseTemplate: String
    deprecatedVersion: String
    listVersionAdded: String
  }

type ListedLicenseException
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardAdditionTemplate: String
    seeAlso: [String]
    obsoletedBy: String
    licenseXml: String
    isDeprecatedAdditionId: Boolean
    additionText: String!
    listVersionAdded: String
    deprecatedVersion: String
  }

type NamespaceMap
  {
    prefix: String!
    namespace: String!
  }

type Organization
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
  }

type OrLaterOperator
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    subjectLicense: License!
  }

type Package
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardName: [String]
    builtTime: String
    validUntilTime: String
    supportLevel: [SupportType]
    suppliedBy: Agent
    originatedBy: [Agent]
    releaseTime: String
    attributionText: [String]
    primaryPurpose: String
    additionalPurpose: [String]
    contentIdentifier: [ContentIdentifier]
    copyrightText: String
    sourceInfo: String
    homePage: String
    downloadLocation: String
    packageVersion: String
    packageUrl: String
  }

type PackageVerificationCode
  {
    comment: String
    packageVerificationCodeExcludedFile: [String]
    hashValue: String!
    algorithm: String!
  }

type Person
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
  }

type PositiveIntegerRange
  {
    endIntegerRange: Int!
    beginIntegerRange: Int!
  }

type Relationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
  }

type Sbom
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    element: [Element]
    profileConformance: [ProfileIdentifierType]
    rootElement: [Element]
    context: String
    sbomType: [SbomType]
  }

type SimpleLicensingText
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    licenseText: String!
  }

type Snippet
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardName: [String]
    builtTime: String
    validUntilTime: String
    supportLevel: [SupportType]
    suppliedBy: Agent
    originatedBy: [Agent]
    releaseTime: String
    attributionText: [String]
    primaryPurpose: String
    additionalPurpose: [String]
    contentIdentifier: [ContentIdentifier]
    copyrightText: String
    lineRange: PositiveIntegerRange
    snippetFromFile: File!
    byteRange: PositiveIntegerRange
  }

type SoftwareAgent
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
  }

interface SoftwareArtifact
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardName: [String]
    builtTime: String
    validUntilTime: String
    supportLevel: [SupportType]
    suppliedBy: Agent
    originatedBy: [Agent]
    releaseTime: String
    attributionText: [String]
    primaryPurpose: String
    additionalPurpose: [String]
    contentIdentifier: [ContentIdentifier]
    copyrightText: String
  }

type SpdxDocument
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    element: [Element]
    profileConformance: [ProfileIdentifierType]
    rootElement: [Element]
    namespaceMap: [NamespaceMap]
    dataLicense: AnyLicenseInfo
    import: [ExternalMap]
  }

type SsvcVulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    decisionType: SsvcDecisionType!
  }

type Tool
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
  }

type VexAffectedVulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    vexVersion: String
    statusNotes: String
    actionStatement: String!
    actionStatementTime: String
  }

type VexFixedVulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    vexVersion: String
    statusNotes: String
  }

type VexNotAffectedVulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    vexVersion: String
    statusNotes: String
    impactStatementTime: String
    justificationType: VexJustificationType
    impactStatement: String
  }

type VexUnderInvestigationVulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    vexVersion: String
    statusNotes: String
  }

interface VexVulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
    vexVersion: String
    statusNotes: String
  }

interface VulnAssessmentRelationship
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    to: [Element]!
    completeness: RelationshipCompleteness
    startTime: String
    relationshipType: String!
    from: Element!
    endTime: String
    withdrawnTime: String
    publishedTime: String
    assessedElement: SoftwareArtifact
    suppliedBy: Agent
    modifiedTime: String
  }

type Vulnerability
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    standardName: [String]
    builtTime: String
    validUntilTime: String
    supportLevel: [SupportType]
    suppliedBy: Agent
    originatedBy: [Agent]
    releaseTime: String
    withdrawnTime: String
    modifiedTime: String
    publishedTime: String
  }

type WithAdditionOperator
  {
    externalIdentifier: [ExternalIdentifier]
    extension: [Extension]
    summary: String
    description: String
    comment: String
    verifiedUsing: [IntegrityMethod]
    externalRef: [ExternalRef]
    name: String
    creationInfo: CreationInfo!
    subjectExtendableLicense: ExtendableLicense!
    subjectAddition: LicenseAddition!
  }
